name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Build and Deploy
      run: |
        echo "Building the web application..."
        mkdir public
        cp index.html public/
        
        echo "Deploying to GitHub Pages..."
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add public/
        git commit -m 'Deploy to GitHub Pages'
        git push origin `git subtree split --prefix public main`:gh-pages --force
